nelmio_cors:
  defaults:
    allow_origin: ['http://localhost:5173']
    allow_methods: ['GET', 'OPTIONS']
    allow_headers: ['Content-Type']
  paths:
    '^/api/':
      allow_origin: ['http://localhost:5173']
